/**
 * Types for importing an image as a module — `import shot from './x.png'`
 * giving back a `StaticImageData` for `next/image`.
 *
 * Next writes this same reference into `next-env.d.ts`, but that file is
 * generated by `next dev` / `next build` and is gitignored, so it does not
 * exist in CI: the workflow installs, generates the Prisma and Basehub
 * clients, and goes straight to `tsc --noEmit`. Without this, a static image
 * import type-checks on a machine that has run the app and fails on one that
 * has not.
 */
/// <reference types="next/image-types/global" />
